### ISSUE TITLE
PythonXP/Python 3.4.4 Incompatability

### ISSUE THREAD

**Issue by GS-ST** [Okmeque1/software#1]
I want to use some programs like PWD.PY and others but they don't run on Windows XP or Python 3.4.4
pls fix this

**Comment by Okmeque1** [comment]
Hello GS-ST, I am sorry to hear that you are having trouble using my programs on your current operating system. Unfortunately my programs aren't supposed to run on something this old. A compatability list with PythonXP/Python 3.4.4 will be added to the COMPTEST.MD file located in the PythonSoft folder

Best regards

-Okmeque1
